.TH "vhtop" "8" "May 2013" "vhtop -- wrapper for the htop program" "System Administration"
.SH "NAME"
.LP
vhtop \- The vhtop utility is simply a wrapper for the htop program.
.SH "SYNTAX"
.LP
vtop [\fIoptions\fP]

.SH "DESCRIPTION"
.LP
vhtop \- The vhtop utility is simply a wrapper for the htop program, that enables htop to show you the all the processes on the system, instead of only the ones in the current s_context (see cat /proc/self/status).
.SH "OPTIONS"
.LP
.TP
See man htop.
.SH "FILES"
.LP
\fI/usr/sbin/vhtop\fP


.SH "EXAMPLES"
.LP
Please contribute some, if you feel it's important.
.SH "AUTHORS"
.LP
This Man page was written by Carlos Alberto Lopez Perez <clopez@igalia.com> based on the vtop(8) manpage.
.SH "SEE ALSO"
.LP
chcontext(8) rebootmgr(8) reducecap(8)
chbind(8) vps(8) vrpm(8) vserver(8)
vserver\-stat(8) vpstree(8) vtop(8)
viotop(8) htop(1)
