.TH "vrpm" "8" "0.1.0" "Klavs Klavsen <kl@vsen.dk>" "System Administration"
.SH "NAME"
.LP 
vrpm \- is simply a wrapper for the rpm utility.
.SH "SYNTAX"
.LP 
vrpm [--unify] [ALL | vserver1 vserver2 ...] \-\- [rpm options]

.SH "DESCRIPTION"
.LP 
vrpm \- is simply a wrapper for the rpm utility. It enables rpm to manage a specific, several or all virtual server(s) with one command.
vrpm is executed in the root server.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-\fR All commands after this, is given to the rpm utility (see man rpm).
.TP
The
\fB--unify\fR option triggers the vunify utility on the vservers and the
supplied packages.
.SH "FILES"
.LP 
\fI/usr/sbin/vrpm\fP 


.SH "EXAMPLES"
.TP 
verifies the gcc package on all vservers.
.LP
vrpm ALL \-\- \-\-verify gcc
.TP
Updates package.rpm on vserver1 and vserver2 if
the package exists in a earlier version 
(the F flag for rpm).
.LP
vrpm vserver1 vserver2 \-\- \-Fvh package.rpm
.TP
vrpm is executed in the root server
.LP 
Please contribute some more, if you feel it's important.
.SH "AUTHORS"
.LP 
This Man page was written by Klavs Klavsen <kl@vsen.dk> and based upon the helpful output from the program itself and the documentation on the Virtual Server site <http://www.solucorp.qc.ca/miscprj/s_context.hc?prjstate=1&nodoc=0>
.SH "SEE ALSO"
.LP 
chcontext(8) rebootmgr(8) reducecap(8)
chbind(8) vps(8) vtop(8) vserver(8)
vserver\-stat(8) vpstree(8)
