#!/bin/bash

proj="util-vserver"
roroot="http://git.linux-vserver.org/git/${proj}.git"

usage() {
	echo "Usage: mkrelease"
}

die() {
	echo $1
	exit ${2:-1}
}

curdir="$PWD"

TMP=`mktemp -d`
cd "$TMP"
git clone ${roroot} || die "git clone failed"
cd ${proj}

ver=`grep AC_INIT configure.ac | awk '{ print $2 }'`
ver=${ver/,}

echo ">>> create release tag"

(cd "$curdir" && git tag -s "$ver") || die "git tag failed"

echo ">>> bootstrap sources"

make -f Makefile.svn || die "make failed"

echo ">>> create release tarball"

./configure --sysconfdir=/etc --prefix=/usr --localstatedir=/var || die "configure failed"
make dist || die "make dist failed"

for i in *.tar.bz2; do
	gpg --detach-sign --armor $i || die "signing failed"
done

echo ">>> uploading tarball and signature"

scp -p *.tar.bz2* ftp.linux-vserver.org:/var/ftp/pub/utils/util-vserver || die "scp failed"

echo ">>> updating documentation"

read -p "Documentation directory (e.g. $HOME/cvs/uv-www/doc):" DOCDIR
./update-doc "$DOCDIR"

cd /
rm -fr "$TMP"
