#!/bin/sh

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
# based on save_s_context by Jacques Gelinas
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

if [ $# -lt 1 ] ;then
	echo save_s_context file command
	echo Save the security context in file and execute a command
else
	CTX=`grep ^s_context: /proc/self/status | sed s/s_context:// | (read a b; echo $a)`
	CTX=`eval expr $CTX + 0`
	echo S_CONTEXT=$CTX >$1
	echo S_PROFILE=$PROFILE >>$1
	shift
	exec "$@"
fi


