#! /bin/bash
# $Id$

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

set -e

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"


function createAptFileSys()
{
    mkdir -p /var/state/apt/lists/partial
    mkdir -p /var/cache/apt/archives/partial
}

vserver="$1"
shift

pkgInit "$vserver" rpm apt

createAptFileSys

exec ${_APT_GET:-apt-get} \
    -o "RPM::RootDir=$VDIR" \
    -o "Dir=$VDIR" \
    -o "Dir::State=$APTSTATEDIR" \
    -o "Dir::Cache=$APTCACHEDIR" \
    -o "Dir::Cache::archives=$APTARCHIVDIR" \
    -o "Dir::Bin::rpm=$RPM_BINARY" \
    -o "Dir::Etc=$APTETCDIR" \
    -o "RPM::Order=true" \
    -o "RPM::PM=external" \
    "$@"
