#!/bin/sh

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
# based on vprofile by Jacques Gelinas
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# Prints or select the active profile for a vserver
if [ $# != 1 -a $# != 2 ] ; then
	echo vprofile vserver [ profile-name ]
else
	if [ ! -f /etc/vservers/$1.conf ] ; then
		echo vserver $1 does not exist >&2
	else
		unset PROFILE
		. /etc/vservers/$1.conf
		if [ $# = 1 ] ; then
			echo PROFILE=$PROFILE
		elif [ $# = 2 ] ; then
			grep .\*\) /etc/vservers/$1.conf
		fi
	fi
fi


