#! /bin/bash
# $Id$

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..."
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"

vserver=$1
cmd=$2

case "$vserver" in
    ./*) VSERVER_DIR=`pwd`/$vserver;;
    /*)  VSERVER_DIR=$vserver;;
    *)	 VSERVER_DIR=$CONFDIR/$vserver;;
esac

test -d "$VSERVER_DIR" || {
    echo "Can not find vserver-setup"
    exit 1
}

if test -e "$VSERVER_DIR"/name; then
    read VSERVER_NAME <"$VSERVER_DIR"/name
else
    VSERVER_NAME=$(basename "$VSERVER_DIR")
fi

case "$2" in
    start)
	. $PKGLIBDIR/vserver.$2
	;;
esac