#!/bin/sh
# chkconfig: - 98 02
# description: Wrapper to start the default vservers
#
### BEGIN INIT INFO
# Provides:          vservers-default
# Required-Start:    $remote_fs $syslog $time $network vprocunhide util-vserver 
# Required-Stop:     $remote_fs $syslog $time $network vprocunhide util-vserver
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Wrapper to start the default vservers
# Description:       Wrapper to start the default vservers
### END INIT INFO

## The *basename* of the lockfile; this must be the same name like
## this if the initscript. Else, the vservers will not be stopped at
## shutdown
#LOCKFILE=vserver-default

## Number of vservers which shall be started in parallel; since most
## initmethods are spending much time time in sleeps, it is safe to
## use a high number here
#NUMPARALLEL=99

## The vserver-flavor; the 'default' vservers will be started very late
## which may be inappropriately for early services like nameservers or
## VPN tunnels. By copying this initscript to a new name and adapting
## the startup-position (for RH/Fedora the numbers in line 2), other
## vservers can be selected. Identification of vservers happens by
## putting the flavor into /etc/vservers/<vserver-id>/apps/init/mark.
#MARK=default

if test -r /etc/sysconfig/vservers-default; then
    . /etc/sysconfig/vservers-default
fi
if test -r /etc/default/vservers-default; then
    . /etc/default/vservers-default
fi

export MARK NUMPARALLEL LOCKFILE
exec /usr/lib/util-vserver/vserver-wrapper "$@"

