.TH "setctxlimit" "1" "0.1.0" "Ola Lundqvist <opal@debian.org>" "System Administration"
.SH "NAME"
.LP 
setctxlimit \- set context limits
.SH "SYNTAX"
.LP 
chcontext [\fIoptions\fP] <\fIlimits\fP>
.SH "DESCRIPTION"
.LP 
setctxlimit set limits for a context.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-ctx\fR context
Specify the context.
.TP 
.SH "AUTHORS"
.LP 
This Man page was written by Ola Lundqvist <opal@debian.org> and based upon the output from the program itself.
.SH "SEE ALSO"
.LP 
chbind(8) rebootmgr(8) reducecap(8)
vps(8) vpstree(8) vrpm(8) vserver(8)
vserver\-stat(8) vtop(8)
