.TH "vps" "8" "0.1.0" "Klavs Klavsen <kl@vsen.dk>" "System Administration"
.SH "NAME"
.LP 
vdu \- The vdu utility is a wrapper for the kill program.
.SH "SYNTAX"
.LP 
vdu [\fIoptions\fP]

.SH "DESCRIPTION"
.LP 
vdu \- The vdu utility is a wrapper for the du program, that enables kill to make disk usage listing on a virtual server.
.SH "OPTIONS"
.LP 
.TP 
See man kill.
.SH "FILES"
.LP 
\fI/usr/sbin/vdu\fP 


.SH "EXAMPLES"
.LP
vdu /vservers/test 
.LP
Please contribute some, if you feel it's important.
.SH "AUTHORS"
.LP 
This Man page was written by Ola Lundqvist using the vps manpage written by Klavs Klavsen <kl@vsen.dk>.
.SH "SEE ALSO"
.LP 
du(8) chcontext(8) rebootmgr(8) reducecap(8)
chbind(8) vpstree(8) vrpm(8) vserver(8)
vserver\-stat(8) vtop(8) vps(8)
