.TH "vps" "8" "0.1.0" "Klavs Klavsen <kl@vsen.dk>" "System Administration"
.SH "NAME"
.LP 
vps \- The vps utility is simply a wrapper for the ps program.
.SH "SYNTAX"
.LP 
vps [\fIoptions\fP]

.SH "DESCRIPTION"
.LP 
vps \- The vps utility is simply a wrapper for the ps program, that enables ps to show you the all the processes on the system, instead of only the ones in the current s_context (see cat /proc/self/status).
.SH "OPTIONS"
.LP 
.TP 
See man ps.
.SH "FILES"
.LP 
\fI/usr/sbin/vps\fP 


.SH "EXAMPLES"
.LP 
Please contribute some, if you feel it's important.
.SH "AUTHORS"
.LP 
This Man page was written by Klavs Klavsen <kl@vsen.dk> and based upon the helpful output from the program itself and the documentation on the Virtual Server site <http://www.solucorp.qc.ca/miscprj/s_context.hc?prjstate=1&nodoc=0>
.SH "SEE ALSO"
.LP 
chcontext(8) rebootmgr(8) reducecap(8)
chbind(8) vpstree(8) vrpm(8) vserver(8)
vserver\-stat(8) vtop(8)
