#!/bin/bash

# Copyright (C) 2007 Natanael Copa <ncopa@alpinelinux.org>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

## Called as: initpost <cfgdir> <path of util-vserver-vars>

vdir="$1"/vdir
. "$2"

# initstyle sanity
initstyle=sysv
test -e "$1"/apps/init/style && initstyle=$(cat "$1"/apps/init/style)

echo ">>> Checking init-style ... $initstyle"

if test "$initstyle" != "sysv" && test "$initstyle" != "plain" ; then
	echo "!!! The init-style is not supported for Alpine Linux"
	echo "!!! Please use sysv or plain"
fi

