#! /bin/bash
# $Id$

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"


function showHelp()
{
    echo \
$"Usage: $0 <vserver-name> -- <params>

vserver-name can be the name of a running guest, or --running to run the command on all running guests.

params is the list of parameters to pass to the apt command that will be run in the guest.

Report bugs to <$PACKAGE_BUGREPORT>."
    exit 0
}

function showVersion()
{
    echo \
$"vapt-get $PACKAGE_VERSION -- apt-get for vservers
This program is part of $PACKAGE_STRING

Copyright (C) 2006 Enrico Scholz
This program is free software; you may redistribute it under the terms of
the GNU General Public License.  This program has absolutely no warranty."
    exit 0
}

tmp=$(getopt -o +q --long help,version,debug,quiet,$VS_ALLVSERVERS_ARGS -n "$0" -- "$@") || exit 1
eval set -- "$tmp"

declare -a send_through vsomething_opts

while true; do
    case "$1" in
	(--help)    	showHelp $0 ;;
	(--version) 	showVersion ;;
	(--debug)	send_through=( "${send_through[@]}" "$1" ); set -x;;
	(--quiet|-q)	send_through=( "${send_through[@]}" "$1" );;
	(--)		shift; break;;
	(*)             vsomething_opts=( "${vsomething_opts[@]}" "$1" );;
    esac
    shift
done

VSOMETHING_TITLE=vapt-get
VSOMETHING_WORKER=$_VAPT_GET_WORKER
VSOMETHING_PKGMGMT=1

export VSOMETHING_TITLE VSOMETHING_WORKER VSOMETHING_PKGMGMT

test ${#vsomething_opts[@]} -eq 0 || vsomething_opts=( "${vsomething_opts[@]}" -- )
exec $_VSOMETHING "${send_through[@]}" ${APT_GET:-apt-get} "${vsomething_opts[@]}" "$@"
