#! /bin/bash

# Copyright (C) 2004 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"

test -n "$MARK" || MARK=default
: ${LOCKFILE:=vservers-$MARK}
: ${NUMPARALLEL:=6}

. "$_LIB_VSERVER_INIT_FUNCTIONS"

function start()
{
    _beginResult $"Starting vservers of type '$MARK'"
    $_START_VSERVERS -m "$MARK" -j "$NUMPARALLEL" --all --start
    _endResult $?
    local rc=$?
    test "$rc" -ne 0 || touch "$lockfile"
    return $rc
}

function stop()
{
    _beginResult $"Stopping vservers of type '$MARK'"
    $_START_VSERVERS -m "$MARK" -j "$NUMPARALLEL" --all --stop
    _endResult $?
    local rc=$?
    $_RM -f "$lockfile"
    return $rc
}

function restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart)	$1;;
    condrestart)
	test -f $lockfile && restart || :
	;;
    status)
	test -f $lockfile && {
	    echo $"vservers of type '$MARK' were started"
	    exit 0
	}
	echo $"vservers of type '$MARK' are not started"
	exit 1
	;;
    *)
        echo "Usage: $0 {start|stop|restart|condrestart|status}"
	exit 2
	;;
esac
