#! /bin/bash
# $Id$

# Copyright (C) 2011 Daniel Hokka Zakrisson <daniel@hozac.com>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

set -e

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"

vserver=$1
shift

pkgInit "$vserver" rpm urpmi
rpmFake.init "$vserver"

urpm="${VURPM_CMD:-urpmi}"

args=( --urpmi-root "$PKGDIR/base" )
if test "$urpm" = "urpmi" -o "$urpm" = "urpme"; then
    args=( "${args[@]}" --root "$VDIR" )
fi

rpmFake.exec $urpm \
    "${args[@]}" \
    "$@"
