#! /bin/bash
# $Id$

# Copyright (C) 2011 Daniel Hokka Zakrisson <daniel@hozac.com>
# Copyright (C) 2005 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"


function showHelp()
{
    echo \
$"Usage: $0 <command> <vserver-name>* [--all] -- <params>+

<command> is any of urpmi/urpme/urpmi.update/urpmf/etc

Report bugs to <$PACKAGE_BUGREPORT>."
    exit 0
}

function showVersion()
{
    echo \
$"vurpm $PACKAGE_VERSION -- urpmi/urpme for vservers
This program is part of $PACKAGE_STRING

Copyright (C) 2005 Enrico Scholz
This program is free software; you may redistribute it under the terms of
the GNU General Public License.  This program has absolutely no warranty."
    exit 0
}

tmp=$(getopt -o +q --long help,version,debug,quiet,all -n "$0" -- "$@") || exit 1
eval set -- "$tmp"

declare -a send_through urpmi_opts

while true; do
    case "$1" in
	(--help)    	showHelp $0 ;;
	(--version) 	showVersion ;;
	(--debug)	send_through=( "${send_through[@]}" "$1" ); set -x;;
	(--quiet|-q)	send_through=( "${send_through[@]}" "$1" );;
	(--all)         urpmi_opts=( "${yum_opts[@]}" "$1" );;
	(--)		shift; break;;
	(*)	   	echo $"vurpm: internal error; arg=='$1'" >&2; exit 1;;
    esac
    shift
done

VSOMETHING_TITLE=vurpm
VSOMETHING_WORKER=$_VURPM_WORKER
VSOMETHING_PKGMGMT=1

export VSOMETHING_TITLE VSOMETHING_WORKER VSOMETHING_PKGMGMT

cmd="$1"
export VURPM_CMD="$cmd"
shift

test ${#urpmi_opts[@]} -eq 0 || urpmi_opts=( "${urpmi_opts[@]}" -- )
exec $_VSOMETHING "${send_through[@]}" "$cmd" "${urpmi_opts[@]}" "$@"
