#! /bin/bash
# $Id$

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

set -e

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
    exit 1
}
. "$UTIL_VSERVER_VARS"
. "$_LIB_FUNCTIONS"

vserver=$1
shift

pkgInit "$vserver" rpm yum
rpmFake.init "$vserver"

test -z "$_YUM" || {
    warning $"The environment variable \$_YUM is not supported anymore; please use \$YUM instead of"
    ${YUM:=$_YUM}
}

function check(){
    python -c "$1" &>/dev/null || {
	warning "\
You are using a version of yum which is insecure and broken in chroot
related operations; either apply the patches shipped in the 'contrib/'
directory of util-vserver, or ask the author of yum to apply them
(preferred).

In the meantime, 'vyum' will continue with dirty hacks which might not
work when the vserver is running and local DOS attacks are possible.

Execution will continue in 5 seconds..."
	sleep 5
	conf=yum-hack.conf
    }
}

yum=${YUM:-yum}
conf=yum.conf
case $($yum --version|tail -n 1) in
    (2.[012345]*)
	check 'import yum,sys; sys.exit(not hasattr(yum.config.yumconf, "getRootedPath"))'
	;;
    (2.[6789]*|3.0*)
	check 'import yum,sys; sys.exit(not hasattr(yum.config.YumConf, "getRootedPath"))'
	;;
    (*)
	warning "\
You are using a version of yum which current status is unknown to vyum.

Just to be sure, 'vyum' will use dirty hacks which might not work when
the vserver is running and local DOS attacks are possible.

Execution will continue in 5 seconds..."
	sleep 5
	conf=yum-hack.conf
	;;
esac

rpmFake.exec $yum \
    -c "$YUMETCDIR/${YUM_CONF:-$conf}" \
    --installroot="$VDIR" \
    "$@"
