#! /bin/bash

# Copyright (C) 2004 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

## Usage: make-manifest <basename> <destdir> <datfile>

name=$1
dest=$2
data=$3

for i in $name-{core,devel,base,build,legacy,lib,sysv}.list; do
    echo '%defattr(-,root,root,-)' >$i
done

sed -e "s!@CONFIG@!$MANIFEST_CONFIG!g;
        s!@CONFIG_NOREPLACE@!$MANIFEST_CONFIG_NOREPLACE!g" \
	$data | \
while read style file; do
    test "$file" || continue
    case "$style" in
	(\#*)	continue;;
    esac
    echo "$file" >>$name-$style.list
done
